# Generated by Django 3.1 on 2020-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('address', models.CharField(max_length=254)),
                ('adharcardno', models.BigIntegerField(unique=True)),
                ('blood_group', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
