# Generated by Django 3.1 on 2020-11-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patregistration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
