# Generated by Django 3.0.11 on 2020-12-07 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticDepartmentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('referred_by', models.CharField(max_length=100)),
                ('handled_by', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('report', models.FileField(upload_to='DiagnosticDepartment/report/')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DD_type', models.CharField(max_length=100)),
                ('DD_license', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('registeration_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
