# Generated by Django 3.1.4 on 2020-12-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0003_auto_20201216_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticdepartmentreport',
            name='patient_name',
        ),
    ]
