# Generated by Django 2.2.6 on 2021-04-17 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0004_remove_diagnosticdepartmentreport_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticdepartmentreport',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_on'),
            preserve_default=False,
        ),
    ]
