# Generated by Django 2.2.6 on 2021-04-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0006_auto_20210417_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticdepartmentreport',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_on'),
        ),
    ]
