# Generated by Django 2.2.6 on 2021-04-17 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0008_auto_20210417_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticdepartmentreport',
            name='create_on',
        ),
        migrations.AddField(
            model_name='diagnosticdepartmentreport',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
