# Generated by Django 2.2.6 on 2021-04-17 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0009_auto_20210417_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticdepartmentreport',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
