# Generated by Django 2.2.6 on 2021-04-17 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0010_auto_20210417_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticdepartment',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
