# Generated by Django 3.2 on 2021-07-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0011_diagnosticdepartment_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticdepartment',
            name='created_on',
        ),
        migrations.AddField(
            model_name='diagnosticdepartmentreport',
            name='patient_history_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosticdepartment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticdepartmentreport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticdepartmentreport',
            name='report',
            field=models.FileField(upload_to=''),
        ),
    ]
