# Generated by Django 3.2 on 2021-04-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticDepartment', '0012_auto_20210420_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticdepartment',
            name='created_on',
        ),
    ]
