# Generated by Django 3.1.1 on 2020-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('doctor_registeration_no', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('experience', models.IntegerField(null=True)),
                ('affiliation', models.CharField(max_length=100, null=True)),
                ('accrediation', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('adharcardno', models.BigIntegerField(unique=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('registeration_number', models.IntegerField()),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('address', models.CharField(max_length=254)),
                ('adharcardno', models.BigIntegerField(unique=True)),
                ('blood_group', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
