# Generated by Django 3.0.11 on 2020-12-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_diagnosticDepartment',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_doctor',
        ),
        migrations.AddField(
            model_name='user',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
