# Generated by Django 3.1.1 on 2020-11-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DD_type', models.CharField(max_length=100)),
                ('DD_license', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100, null=True)),
                ('supervisor', models.CharField(max_length=100)),
                ('referred_by', models.CharField(max_length=100)),
                ('handled_by', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_status', models.IntegerField()),
                ('symtomps', models.CharField(max_length=1000)),
                ('disease', models.CharField(max_length=200)),
                ('affected_area', models.CharField(max_length=200)),
                ('report', models.FileField(max_length=500, null=True, upload_to=None)),
                ('timespan', models.CharField(max_length=100)),
                ('precription', models.CharField(max_length=1000)),
                ('course_duration', models.CharField(max_length=100)),
                ('follow_up', models.CharField(max_length=100, null=True)),
                ('referred_from', models.CharField(max_length=100, null=True)),
                ('referred_to', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
