# Generated by Django 3.1.4 on 2020-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0002_diagnosticdepartment_patienthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticdepartment',
            name='report',
            field=models.FileField(default='DiagnosticDepartment/report/xyz.txt', upload_to='DiagnosticDepartment/report/'),
        ),
    ]
