# Generated by Django 3.0.11 on 2020-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0002_diagnosticdepartment_patienthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('1', 'Patient'), ('2', 'Doctor')], default='1', max_length=6)),
            ],
        ),
    ]
