# Generated by Django 3.0.11 on 2020-12-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0002_auto_20201207_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticDepartment',
        ),
    ]
