# Generated by Django 3.1 on 2020-12-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0003_delete_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
