# Generated by Django 3.0.11 on 2020-12-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0003_delete_diagnosticdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypemodel',
            name='usertype',
            field=models.CharField(choices=[(2, 'Doctor'), (3, 'Hospital'), (4, 'Diagnostic Department')], default='2', max_length=6),
        ),
    ]
