# Generated by Django 3.1 on 2020-12-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0005_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
