# Generated by Django 3.1 on 2020-12-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0003_usertypemodel'),
        ('ARCIT', '0003_diagnosticdepartment_report'),
        ('ARCIT', '0006_auto_20201204_1751'),
    ]

    operations = [
    ]
