# Generated by Django 3.2 on 2021-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypemodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
