# Generated by Django 3.2 on 2021-08-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARCIT', '0010_alter_usertypemodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTypeModel',
        ),
    ]
