# Generated by Django 3.1 on 2020-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('doctor_registeration_no', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('affiliation', models.CharField(max_length=100)),
                ('accrediation', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('adharcardno', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
