# Generated by Django 3.0.11 on 2020-12-10 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0003_patienthistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
