# Generated by Django 3.0.11 on 2020-12-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0004_auto_20201210_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
