# Generated by Django 3.1.4 on 2020-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20201210_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='report',
            field=models.FileField(default='', upload_to='PatientHistory/report/'),
        ),
    ]
