# Generated by Django 3.1.4 on 2020-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patienthistory_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='report',
            field=models.FileField(default='', null=True, upload_to='PatientHistory/report/'),
        ),
    ]
