# Generated by Django 3.1.4 on 2020-12-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_remove_patienthistory_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='report',
            field=models.FileField(default='', null=True, upload_to='PatientHistory/report/'),
        ),
    ]
