# Generated by Django 3.1.4 on 2020-12-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_patienthistory_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='report',
        ),
    ]
