# Generated by Django 3.1.4 on 2020-12-15 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0010_remove_patienthistory_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='referred_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_from', to='ARCIT.user'),
        ),
    ]
