# Generated by Django 3.2 on 2021-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_auto_20210417_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
