# Generated by Django 3.2 on 2021-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_auto_20210418_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nonce',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_hash',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
