# Generated by Django 3.2 on 2021-04-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_auto_20210418_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthistory',
            old_name='precription',
            new_name='prescription',
        ),
    ]
