# Generated by Django 3.2 on 2021-04-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_rename_precription_patienthistory_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_on',
        ),
    ]
