# Generated by Django 3.2 on 2021-04-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_auto_20210418_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='previous_hash',
        ),
    ]
