# Generated by Django 3.2 on 2021-07-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0018_auto_20210423_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='nonce',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='previous_hash',
            field=models.CharField(default='0', max_length=254),
            preserve_default=False,
        ),
    ]
