# Generated by Django 3.2 on 2021-08-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0021_alter_patient_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.IntegerField(default=400000),
        ),
    ]
