# Generated by Django 3.2 on 2021-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0022_patient_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
