# Generated by Django 3.2 on 2021-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0023_alter_patient_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.BigIntegerField()),
                ('doctor_id', models.BigIntegerField()),
                ('active_hour_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('startDAT', models.DateTimeField()),
                ('endDAT', models.DateTimeField()),
                ('token_number', models.BigIntegerField()),
            ],
        ),
    ]
