# Generated by Django 3.2 on 2021-08-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0024_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='endDAT',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='startDAT',
        ),
    ]
