# Generated by Django 3.2 on 2021-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0025_auto_20210824_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
    ]
