# Generated by Django 2.2.6 on 2021-04-17 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
