# Generated by Django 3.2 on 2021-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctor_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
