# Generated by Django 3.2 on 2021-04-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_alter_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='adharcardno',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_registeration_no',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
