# Generated by Django 3.2 on 2021-04-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20210421_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='created_on',
        ),
    ]
