# Generated by Django 3.2 on 2021-06-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_auto_20210423_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='accrediation',
            new_name='accreditation',
        ),
    ]
