# Generated by Django 3.2 on 2021-08-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_rename_accrediation_doctor_accreditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
