# Generated by Django 3.2 on 2021-08-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_auto_20210815_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='active_hours_id',
            new_name='active_hours',
        ),
    ]
