# Generated by Django 3.2 on 2021-08-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0011_rename_active_hours_id_doctor_active_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveHour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('for_hospital', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveHours',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='active_hours',
            field=models.JSONField(default='[]'),
        ),
    ]
