# Generated by Django 3.2 on 2021-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0013_auto_20210815_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activehour',
            name='for_hospital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
