# Generated by Django 3.2 on 2021-08-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_alter_activehour_for_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='active_hours',
            field=models.JSONField(default=[]),
        ),
    ]
