# Generated by Django 3.2 on 2021-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0015_alter_doctor_active_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='active_hours',
            field=models.JSONField(default=list),
        ),
    ]
