# Generated by Django 3.2 on 2021-08-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_rename_userid_activehour_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pincode',
            field=models.IntegerField(default=400000),
        ),
    ]
