# Generated by Django 3.2 on 2021-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_doctor_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
